# Generated by Django 5.2 on 2025-08-16 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=10, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_options', models.BooleanField(default=False)),
                ('requires_multiple_answers', models.BooleanField(default=False)),
                ('requires_word_limit', models.BooleanField(default=False)),
                ('requires_image', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='ReadingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='IELTS Academic Reading Test', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('MC', 'Multiple Choice'), ('TFNG', 'True/False/Not Given'), ('YNN', 'Yes/No/Not Given'), ('MH', 'Matching Headings'), ('MP', 'Matching Paragraphs'), ('MF', 'Matching Features'), ('MSE', 'Matching Sentence Endings'), ('SC', 'Sentence Completion'), ('SUMC', 'Summary Completion'), ('NC', 'Note Completion'), ('TC', 'Table Completion'), ('FCC', 'Flow Chart Completion'), ('DL', 'Diagram Labelling'), ('SA', 'Short Answer'), ('PFL', 'Pick from List'), ('CUSTOM', 'Custom Question Type')], default='MC', max_length=10)),
                ('custom_question_type', models.CharField(blank=True, max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.CharField(blank=True, max_length=255)),
                ('correct_answers', models.JSONField(blank=True, default=list)),
                ('points', models.PositiveIntegerField(default=1)),
                ('word_limit', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('order', models.PositiveIntegerField(default=1)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reading.passage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='passage',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='reading.readingtest'),
        ),
    ]
