# Generated by Django 4.2.4 on 2025-12-06 01:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('passage_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, help_text="Optional subtitle for the passage (e.g., 'The Impact on Global Ecosystems')", max_length=255, null=True)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('has_paragraphs', models.BooleanField(default=False)),
                ('paragraph_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('paragraph_labels', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reading Passage',
                'verbose_name_plural': 'Reading Passages',
                'db_table': 'reading_passage',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('question_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, help_text="Title for note completion questions (e.g., 'Notes about Climate Change')", max_length=255, null=True)),
                ('instruction_template', models.TextField()),
                ('expected_range', models.CharField(max_length=20)),
                ('student_range', models.CharField(blank=True, max_length=20, null=True)),
                ('actual_count', models.PositiveIntegerField(default=0)),
                ('questions_data', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='diagrams/')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reading.passage')),
            ],
            options={
                'verbose_name': 'Question Type',
                'verbose_name_plural': 'Question Types',
                'db_table': 'reading_question_type',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReadingTest',
            fields=[
                ('test_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(default='IELTS Academic Reading Test', max_length=255)),
                ('source', models.CharField(default='Custom Test', max_length=255)),
                ('organization_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reading Test',
                'verbose_name_plural': 'Reading Tests',
                'db_table': 'reading_test',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmitAnswer',
            fields=[
                ('submit_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this submission', primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Session ID from Academiq exam session', max_length=100)),
                ('test_id', models.UUIDField(help_text='UUID of the ReadingTest that was taken')),
                ('student_id', models.IntegerField(help_text='ID of the student who took the test')),
                ('organization_id', models.IntegerField(help_text='Organization ID that owns this submission')),
                ('total_questions', models.IntegerField(help_text='Number of questions answered by student (1-40)')),
                ('is_processed', models.BooleanField(blank=True, default=False, help_text='Whether this submission has been processed for scoring', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When this submission was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this submission was last modified')),
            ],
            options={
                'verbose_name': 'Submit Answer',
                'verbose_name_plural': 'Submit Answers',
                'db_table': 'submit_answers',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['session_id'], name='submit_answ_session_3db22e_idx'), models.Index(fields=['test_id'], name='submit_answ_test_id_58acb5_idx'), models.Index(fields=['student_id'], name='submit_answ_student_33eaf3_idx'), models.Index(fields=['organization_id'], name='submit_answ_organiz_bc4c9d_idx'), models.Index(fields=['session_id', 'is_processed'], name='submit_answ_session_452507_idx')],
            },
        ),
        migrations.AddField(
            model_name='passage',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='reading.readingtest'),
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('answer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_number', models.IntegerField(help_text='Global question number (1-40)')),
                ('student_answer', models.JSONField(help_text='Enhanced student answer data with metadata')),
                ('session_id', models.CharField(help_text='Session ID from Academiq', max_length=36)),
                ('is_correct', models.BooleanField(default=False, help_text='Whether the answer is correct')),
                ('band_score', models.DecimalField(blank=True, decimal_places=1, help_text='Band score for this answer', max_digits=3, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When the answer was submitted')),
                ('scored_at', models.DateTimeField(blank=True, help_text='When the answer was scored', null=True)),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='reading.questiontype')),
                ('submit_answer', models.ForeignKey(blank=True, help_text='Link to the submission this answer belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='reading.submitanswer')),
            ],
            options={
                'verbose_name': 'Student Answer',
                'verbose_name_plural': 'Student Answers',
                'db_table': 'reading_student_answers',
                'ordering': ['question_number'],
                'indexes': [models.Index(fields=['submit_answer', 'question_number'], name='reading_stu_submit__a57e25_idx'), models.Index(fields=['question_type', 'question_number'], name='reading_stu_questio_340532_idx'), models.Index(fields=['submitted_at'], name='reading_stu_submitt_dc3b40_idx'), models.Index(fields=['session_id'], name='reading_stu_session_65ad83_idx')],
                'unique_together': {('session_id', 'question_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='passage',
            unique_together={('test', 'order')},
        ),
    ]
