# Generated by Django 5.2 on 2025-08-17 12:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('passage_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('instruction', models.TextField()),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Reading Passage',
                'verbose_name_plural': 'Reading Passages',
                'db_table': 'reading_passage',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=10, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_options', models.BooleanField(default=False)),
                ('requires_multiple_answers', models.BooleanField(default=False)),
                ('requires_word_limit', models.BooleanField(default=False)),
                ('requires_image', models.BooleanField(default=False)),
                ('default_instruction', models.TextField(blank=True, help_text='Default IELTS instruction text for this question type')),
                ('default_answer_format', models.TextField(blank=True, help_text='Default format instructions for how to answer this question type')),
                ('template_examples', models.JSONField(blank=True, default=list, help_text='JSON array of template examples for this question type')),
                ('word_limit_rules', models.JSONField(blank=True, default=dict, help_text='Word limit rules and configurations for this question type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='ReadingTest',
            fields=[
                ('test_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(default='IELTS Academic Reading Test', max_length=255)),
                ('source', models.CharField(default='Custom Test', max_length=255)),
                ('organization_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reading Test',
                'verbose_name_plural': 'Reading Tests',
                'db_table': 'reading_test',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('question_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('instruction_template', models.TextField()),
                ('expected_range', models.CharField(max_length=20)),
                ('actual_count', models.PositiveIntegerField(default=0)),
                ('questions_data', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=1)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reading.passage')),
            ],
            options={
                'verbose_name': 'Question Type',
                'verbose_name_plural': 'Question Types',
                'db_table': 'reading_question_type',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='passage',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='reading.readingtest'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('number', models.PositiveIntegerField()),
                ('answer', models.CharField(max_length=255)),
                ('options', models.JSONField(blank=True, default=list)),
                ('word_limit', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('points', models.PositiveIntegerField(default=1)),
                ('explanation', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_questions', to='reading.questiontype')),
            ],
            options={
                'verbose_name': 'Individual Question',
                'verbose_name_plural': 'Individual Questions',
                'db_table': 'reading_question',
                'ordering': ['number'],
                'unique_together': {('question_type', 'number')},
            },
        ),
    ]
