# Generated by Django 5.2 on 2025-08-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='organization_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
