# Generated by Django 5.2 on 2025-08-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_alter_passage_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diagrams/'),
        ),
    ]
