# Generated by Django 5.2 on 2025-08-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_questiontype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontype',
            name='student_range',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
