# Generated by Django 5.2 on 2025-08-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_question_created_at_question_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readingtest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='readingtest',
            name='organization_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readingtest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
