# Generated by Django 5.2 on 2025-08-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0004_alter_readingtest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order_number']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_format',
            field=models.TextField(blank=True, help_text='Format instructions for how to answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='instruction',
            field=models.TextField(blank=True, help_text='IELTS instruction text for this question type'),
        ),
        migrations.AddField(
            model_name='question',
            name='order_number',
            field=models.PositiveIntegerField(default=1, help_text='Sequential order across all question types'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_range',
            field=models.CharField(blank=True, help_text="Auto-calculated range like 'Questions 1-7'", max_length=50),
        ),
        migrations.AddField(
            model_name='questiontypeconfig',
            name='default_answer_format',
            field=models.TextField(blank=True, help_text='Default format instructions for how to answer this question type'),
        ),
        migrations.AddField(
            model_name='questiontypeconfig',
            name='default_instruction',
            field=models.TextField(blank=True, help_text='Default IELTS instruction text for this question type'),
        ),
        migrations.AddField(
            model_name='questiontypeconfig',
            name='template_examples',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of template examples for this question type'),
        ),
        migrations.AddField(
            model_name='questiontypeconfig',
            name='word_limit_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Word limit rules and configurations for this question type'),
        ),
    ]
