# Generated by Django 5.2 on 2025-08-23 04:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0005_fix_passage_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passage',
            name='organization_id',
        ),
        migrations.AlterField(
            model_name='passage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passage',
            name='has_paragraphs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passage',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='passage',
            name='paragraph_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='paragraph_labels',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='passage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
