# Generated by Django 5.2 on 2025-08-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0006_remove_passage_organization_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontype',
            name='title',
            field=models.CharField(blank=True, help_text="Title for note completion questions (e.g., 'Notes about Climate Change')", max_length=255, null=True),
        ),
    ]
