# Generated by Django 5.2 on 2025-08-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0007_questiontype_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='subtitle',
            field=models.CharField(blank=True, help_text="Optional subtitle for the passage (e.g., 'The Impact on Global Ecosystems')", max_length=255, null=True),
        ),
    ]
