# Generated by Django 5.2 on 2025-08-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_create_test_registry'),
        ('reading', '0008_passage_subtitle'),
    ]

    operations = [
    ]
