# Generated by Django 4.2.4 on 2025-08-29 14:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0009_merge_0002_create_test_registry_0008_passage_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('answer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_number', models.IntegerField(help_text='Global question number (1-40)')),
                ('student_answer', models.JSONField(help_text="Student's submitted answer (string or array)")),
                ('session_id', models.CharField(help_text='Session ID from Academiq', max_length=36)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When this answer was submitted')),
                ('scored_at', models.DateTimeField(blank=True, help_text='When this answer was compared and scored', null=True)),
                ('is_correct', models.BooleanField(default=False, help_text="Whether student's answer is correct")),
                ('band_score', models.DecimalField(blank=True, decimal_places=1, help_text='Band score for this question', max_digits=3, null=True)),
            ],
            options={
                'verbose_name': 'Student Answer',
                'verbose_name_plural': 'Student Answers',
                'db_table': 'reading_student_answers',
                'ordering': ['question_number'],
            },
        ),
        migrations.RemoveIndex(
            model_name='testregistry',
            name='test_registry_balancing_idx',
        ),
        migrations.RenameIndex(
            model_name='testregistry',
            new_name='test_regist_organiz_cb143f_idx',
            old_name='test_registry_org_idx',
        ),
        migrations.RenameIndex(
            model_name='testregistry',
            new_name='test_regist_is_acti_33e586_idx',
            old_name='test_registry_active_idx',
        ),
        migrations.RenameIndex(
            model_name='testregistry',
            new_name='test_regist_usage_c_4ebcb3_idx',
            old_name='test_registry_usage_idx',
        ),
        migrations.RenameIndex(
            model_name='testregistry',
            new_name='test_regist_organiz_cbe8b4_idx',
            old_name='test_registry_org_active_idx',
        ),
        migrations.AlterField(
            model_name='testregistry',
            name='test_id',
            field=models.UUIDField(help_text='Unique identifier for the test (links to ReadingTest.test_id)', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='reading.questiontype'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['session_id', 'question_number'], name='reading_stu_session_1b5536_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['question_type', 'question_number'], name='reading_stu_questio_340532_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['submitted_at'], name='reading_stu_submitt_dc3b40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('session_id', 'question_number')},
        ),
    ]
