# Generated by Django 4.2.4 on 2025-08-29 17:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0010_add_student_answer_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitAnswer',
            fields=[
                ('submit_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this submission', primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Session ID from Academiq exam session', max_length=100)),
                ('test_id', models.UUIDField(help_text='UUID of the ReadingTest that was taken')),
                ('student_id', models.IntegerField(help_text='ID of the student who took the test')),
                ('organization_id', models.IntegerField(help_text='Organization ID that owns this submission')),
                ('total_questions', models.IntegerField(help_text='Number of questions answered by student (1-40)')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether this submission has been processed for scoring')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When this submission was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this submission was last modified')),
            ],
            options={
                'verbose_name': 'Submit Answer',
                'verbose_name_plural': 'Submit Answers',
                'db_table': 'submit_answers',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='studentanswer',
            name='reading_stu_session_1b5536_idx',
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['session_id'], name='reading_stu_session_65ad83_idx'),
        ),
        migrations.AddIndex(
            model_name='submitanswer',
            index=models.Index(fields=['session_id'], name='submit_answ_session_3db22e_idx'),
        ),
        migrations.AddIndex(
            model_name='submitanswer',
            index=models.Index(fields=['test_id'], name='submit_answ_test_id_58acb5_idx'),
        ),
        migrations.AddIndex(
            model_name='submitanswer',
            index=models.Index(fields=['student_id'], name='submit_answ_student_33eaf3_idx'),
        ),
        migrations.AddIndex(
            model_name='submitanswer',
            index=models.Index(fields=['organization_id'], name='submit_answ_organiz_bc4c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='submitanswer',
            index=models.Index(fields=['session_id', 'is_processed'], name='submit_answ_session_452507_idx'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='submit_answer',
            field=models.ForeignKey(blank=True, help_text='Link to the submission this answer belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='reading.submitanswer'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['submit_answer', 'question_number'], name='reading_stu_submit__a57e25_idx'),
        ),
    ]
