# Generated by Django 4.2.4 on 2025-09-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0011_submitanswer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='band_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Band score for this answer', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='Whether the answer is correct'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='scored_at',
            field=models.DateTimeField(blank=True, help_text='When the answer was scored', null=True),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='student_answer',
            field=models.JSONField(help_text='Enhanced student answer data with metadata'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the answer was submitted'),
        ),
        migrations.AlterField(
            model_name='submitanswer',
            name='is_processed',
            field=models.BooleanField(blank=True, default=False, help_text='Whether this submission has been processed for scoring', null=True),
        ),
    ]
