# Generated by Django 4.2.4 on 2025-09-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0012_alter_studentanswer_band_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontype',
            name='headings_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
