# Generated by Django 4.2.4 on 2025-09-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0013_questiontype_headings_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontype',
            name='headings_list',
        ),
    ]
