# Generated by Django 4.2.4 on 2025-11-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0014_remove_questiontype_headings_list'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.DeleteModel(
            name='QuestionTypeConfig',
        ),
        migrations.DeleteModel(
            name='TestRegistry',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
