# Generated by Django 4.2.4 on 2025-11-23 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0015_remove_deleted_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passage',
            name='instruction',
        ),
    ]
